#
# Module manifest for module 'ResizeTerminal'
#
# Generated by: Terminal Resizer
#
# Generated on: 5/2/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule        = 'ResizeTerminal.psm1'
    
    # Version number of this module.
    ModuleVersion     = '1.0.0'
    
    # ID used to uniquely identify this module
    GUID              = '41d4d637-7a3e-4cdc-90df-2c393532dd59'
    
    # Author of this module
    Author            = 'nimbul'
    
    # Company or vendor of this module
    CompanyName       = 'nimbul'
    
    # Copyright statement for this module
    Copyright         = '(c) 2025 nimbul. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description       = 'Provides terminal window resizing functionality for PowerShell commands. Temporarily shrinks the terminal window to a ribbon to keep the command line visible but minimal.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Scripts to run before importing this module
    ScriptsToProcess  = @('CompatibilityCheck.ps1')
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Resize-Terminal',
        'New-ResizeShim',
        'Get-ResizeShim',
        'Remove-ResizeShim'
    )
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()
    
    # Variables to export from this module
    VariablesToExport = @()
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('Terminal', 'Console', 'Resize', 'Window')
            
            # A URL to the license for this module.
            LicenseUri   = 'https://opensource.org/licenses/MIT'
            
            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/nimbuldev/wt-shrink'
            
            # ReleaseNotes of this module
            ReleaseNotes = @'
# Release Notes
1.0.0 - Initial release of the ResizeTerminal module.
- Terminal window resizing with animation support
- Create shims for existing commands
- Conditional resizing based on command arguments
- Windows Terminal Quake compatibility
'@
        } # End of PSData hashtable
        
    } # End of PrivateData hashtable
}